OpenSceneGraph: osgIntrospection::AtomicValueReflector< T > Struct Template Reference
osgIntrospection::AtomicValueReflector< T > Struct Template Reference
This reflector is a ValueReflector that should be used to define types that can be read and written from/to streams using the << and >> operators.
Public Types
typedef ValueReflector< T >
::instance_creator_type instance_creator_type
Public Member Functions
AtomicValueReflector (const std::string &name, const std::string &ns)
AtomicValueReflector (const std::string &qname)
Detailed Description
template<typename T>
struct osgIntrospection::AtomicValueReflector< T >
This reflector is a ValueReflector that should be used to define types that can be read and written from/to streams using the << and >> operators.
A StdReaderWriter is assigned by default.
Member Typedef Documentation
template<typename T > typedef ValueReflector<T>::instance_creator_type osgIntrospection::AtomicValueReflector< T >::instance_creator_type
Reimplemented from osgIntrospection::ValueReflector< T >.
Constructor & Destructor Documentation
template<typename T > osgIntrospection::AtomicValueReflector< T >::AtomicValueReflector (const std::string & name, const std::string & ns) [inline]
References osgIntrospection::Reflector< T >::addConstructor(), osgIntrospection::Reflector< T >::setComparator(), and osgIntrospection::Reflector< T >::setReaderWriter().
template<typename T > osgIntrospection::AtomicValueReflector< T >::AtomicValueReflector (const std::string & qname) [inline]
References osgIntrospection::Reflector< T >::addConstructor(), osgIntrospection::Reflector< T >::setComparator(), and osgIntrospection::Reflector< T >::setReaderWriter().
The documentation for this struct was generated from the following file:
osgIntrospection/Reflector
Generated at Thu Jun 9 2011 10:20:40 for the OpenSceneGraph by doxygen 1.7.3.