OpenSceneGraph: osgSim::AzimRange Class Reference
osgSim::AzimRange Class Reference
Public Member Functions
AzimRange ()
void setAzimuthRange (float minAzimuth, float maxAzimuth, float fadeAngle=0.0f)
void getAzimuthRange (float &minAzimuth, float &maxAzimuth, float &fadeAngle) const
float azimSector (const osg::Vec3 &eyeLocal) const
Protected Attributes
float _cosAzim
float _sinAzim
float _cosAngle
float _cosFadeAngle
Constructor & Destructor Documentation
osgSim::AzimRange::AzimRange () [inline]
Member Function Documentation
float osgSim::AzimRange::azimSector (const osg::Vec3 & eyeLocal) const [inline]
References osg::square(), osg::Vec3f::x(), and osg::Vec3f::y().
void osgSim::AzimRange::getAzimuthRange (float & minAzimuth, float & maxAzimuth, float & fadeAngle) const
void osgSim::AzimRange::setAzimuthRange (float minAzimuth, float maxAzimuth, float fadeAngle = 0.0f)
Member Data Documentation
float osgSim::AzimRange::_cosAngle [protected]
float osgSim::AzimRange::_cosAzim [protected]
float osgSim::AzimRange::_cosFadeAngle [protected]
float osgSim::AzimRange::_sinAzim [protected]
The documentation for this class was generated from the following file:
osgSim/Sector
Generated at Thu Jun 9 2011 10:20:42 for the OpenSceneGraph by doxygen 1.7.3.