OpenSceneGraph: osgManipulator::Constraint Class Reference
osgManipulator::Constraint Class Reference
Public Member Functions
virtual bool constrain (MotionCommand &) const
virtual bool constrain (TranslateInLineCommand &command) const
virtual bool constrain (TranslateInPlaneCommand &command) const
virtual bool constrain (Scale1DCommand &command) const
virtual bool constrain (Scale2DCommand &command) const
virtual bool constrain (ScaleUniformCommand &command) const
Protected Member Functions
Constraint (osg::Node &refNode)
virtual ~Constraint ()
osg::Node & getReferenceNode ()
const osg::Node & getReferenceNode () const
const osg::Matrix & getLocalToWorld () const
const osg::Matrix & getWorldToLocal () const
void computeLocalToWorldAndWorldToLocal () const
Constructor & Destructor Documentation
osgManipulator::Constraint::Constraint (osg::Node & refNode) [inline, protected]
virtual osgManipulator::Constraint::~Constraint () [inline, protected, virtual]
Member Function Documentation
void osgManipulator::Constraint::computeLocalToWorldAndWorldToLocal () const [protected]
virtual bool osgManipulator::Constraint::constrain (Scale2DCommand & command) const [inline, virtual]
Reimplemented in osgManipulator::GridConstraint.
References constrain().
Referenced by constrain().
virtual bool osgManipulator::Constraint::constrain (MotionCommand &) const [inline, virtual]
virtual bool osgManipulator::Constraint::constrain (Scale1DCommand & command) const [inline, virtual]
Reimplemented in osgManipulator::GridConstraint.
References constrain().
Referenced by constrain().
virtual bool osgManipulator::Constraint::constrain (TranslateInLineCommand & command) const [inline, virtual]
Reimplemented in osgManipulator::GridConstraint.
References constrain().
Referenced by constrain().
virtual bool osgManipulator::Constraint::constrain (TranslateInPlaneCommand & command) const [inline, virtual]
Reimplemented in osgManipulator::GridConstraint.
References constrain().
Referenced by constrain().
virtual bool osgManipulator::Constraint::constrain (ScaleUniformCommand & command) const [inline, virtual]
Reimplemented in osgManipulator::GridConstraint.
References constrain().
Referenced by constrain().
const osg::Matrix& osgManipulator::Constraint::getLocalToWorld () const [inline, protected]
const osg::Node& osgManipulator::Constraint::getReferenceNode () const [inline, protected]
osg::Node& osgManipulator::Constraint::getReferenceNode () [inline, protected]
const osg::Matrix& osgManipulator::Constraint::getWorldToLocal () const [inline, protected]
The documentation for this class was generated from the following file:
osgManipulator/Constraint
Generated at Thu Jun 9 2011 10:20:41 for the OpenSceneGraph by doxygen 1.7.3.