OpenSceneGraph: osgIntrospection::EnumReflector< T > Struct Template Reference
osgIntrospection::EnumReflector< T > Struct Template Reference
This reflector is a ValueReflector that should be used to define enumerations.
Public Types
typedef EnumReflector< T > inherited
typedef ValueReflector< T >
::instance_creator_type instance_creator_type
Public Member Functions
EnumReflector (const std::string &name, const std::string &ns)
EnumReflector (const std::string &qname)
Detailed Description
template<typename T>
struct osgIntrospection::EnumReflector< T >
This reflector is a ValueReflector that should be used to define enumerations.
It assigns an EnumReaderWriter by default.
Member Typedef Documentation
template<typename T > typedef EnumReflector<T> osgIntrospection::EnumReflector< T >::inherited
Reimplemented from osgIntrospection::ValueReflector< T >.
template<typename T > typedef ValueReflector<T>::instance_creator_type osgIntrospection::EnumReflector< T >::instance_creator_type
Reimplemented from osgIntrospection::ValueReflector< T >.
Constructor & Destructor Documentation
template<typename T > osgIntrospection::EnumReflector< T >::EnumReflector (const std::string & name, const std::string & ns) [inline]
References osgIntrospection::Reflector< T >::addConstructor(), osgIntrospection::Reflector< T >::setComparator(), and osgIntrospection::Reflector< T >::setReaderWriter().
template<typename T > osgIntrospection::EnumReflector< T >::EnumReflector (const std::string & qname) [inline]
References osgIntrospection::Reflector< T >::addConstructor(), osgIntrospection::Reflector< T >::setComparator(), and osgIntrospection::Reflector< T >::setReaderWriter().
The documentation for this struct was generated from the following file:
osgIntrospection/Reflector
Generated at Thu Jun 9 2011 10:20:40 for the OpenSceneGraph by doxygen 1.7.3.