OpenSceneGraph: osg::DrawElements Class Reference
osg::DrawElements Class Reference
Public Member Functions
DrawElements (Type primType=PrimitiveType, GLenum mode=0, int numInstances=0)
DrawElements (const DrawElements &copy, const CopyOp &copyop=CopyOp::SHALLOW_COPY)
virtual DrawElements * getDrawElements ()
virtual const DrawElements * getDrawElements () const
virtual void dirty ()
Dirty the primitive, which increments the modified count, to force buffer objects to update.
void setElementBufferObject (osg::ElementBufferObject *ebo)
Set the ElementBufferObject.
osg::ElementBufferObject * getElementBufferObject ()
Get the ElementBufferObject.
const osg::ElementBufferObject * getElementBufferObject () const
Get the const ElementBufferObject.
void setElementBufferObjectOffset (const GLvoid *offset) const
Set the offset into the ElementBufferObject, if used.
const GLvoid * getElementBufferObjectOffset () const
Get the offset into the ElementBufferOffset, if used.
virtual void resizeGLObjectBuffers (unsigned int maxSize)
Resize any per context GLObject buffers to specified size.
virtual void releaseGLObjects (State *state=0) const
If State is non-zero, this function releases OpenGL objects for the specified graphics context.
virtual void reserveElements (unsigned int numIndices)=0
virtual void setElement (unsigned int, unsigned int)=0
virtual unsigned int getElement (unsigned int)=0
virtual void addElement (unsigned int)=0
Protected Member Functions
virtual ~DrawElements ()
Protected Attributes
osg::ref_ptr< ElementBufferObject > _ebo
const GLvoid * _eboOffset
Constructor & Destructor Documentation
osg::DrawElements::DrawElements (Type primType = PrimitiveType, GLenum mode = 0, int numInstances = 0) [inline]
osg::DrawElements::DrawElements (const DrawElements & copy, const CopyOp & copyop = CopyOp::SHALLOW_COPY) [inline]
virtual osg::DrawElements::~DrawElements () [inline, protected, virtual]
References _ebo, and osg::ref_ptr< T >::valid().
Member Function Documentation
virtual void osg::DrawElements::addElement (unsigned int) [pure virtual]
Implemented in osg::DrawElementsUByte, osg::DrawElementsUShort, and osg::DrawElementsUInt.
virtual void osg::DrawElements::dirty () [inline, virtual]
Dirty the primitive, which increments the modified count, to force buffer objects to update.
Reimplemented from osg::PrimitiveSet.
References _ebo, osg::PrimitiveSet::_modifiedCount, and osg::ref_ptr< T >::valid().
virtual const DrawElements* osg::DrawElements::getDrawElements () const [inline, virtual]
Reimplemented from osg::PrimitiveSet.
virtual DrawElements* osg::DrawElements::getDrawElements () [inline, virtual]
Reimplemented from osg::PrimitiveSet.
virtual unsigned int osg::DrawElements::getElement (unsigned int) [pure virtual]
Implemented in osg::DrawElementsUByte, osg::DrawElementsUShort, and osg::DrawElementsUInt.
const osg::ElementBufferObject* osg::DrawElements::getElementBufferObject () const [inline]
Get the const ElementBufferObject.
If no EBO is assigned returns NULL
References _ebo, and osg::ref_ptr< T >::get().
osg::ElementBufferObject* osg::DrawElements::getElementBufferObject () [inline]
Get the ElementBufferObject.
If no EBO is assigned returns NULL
References _ebo, and osg::ref_ptr< T >::get().
const GLvoid* osg::DrawElements::getElementBufferObjectOffset () const [inline]
Get the offset into the ElementBufferOffset, if used.
References _eboOffset.
virtual void osg::DrawElements::releaseGLObjects (State * state = 0) const [inline, virtual]
If State is non-zero, this function releases OpenGL objects for the specified graphics context.
Otherwise, releases OpenGL objects for all graphics contexts.
Reimplemented from osg::PrimitiveSet.
References _ebo, and osg::ref_ptr< T >::valid().
virtual void osg::DrawElements::reserveElements (unsigned int numIndices) [pure virtual]
Implemented in osg::DrawElementsUByte, osg::DrawElementsUShort, and osg::DrawElementsUInt.
virtual void osg::DrawElements::resizeGLObjectBuffers (unsigned int maxSize) [inline, virtual]
Resize any per context GLObject buffers to specified size.
Reimplemented from osg::PrimitiveSet.
References _ebo, and osg::ref_ptr< T >::valid().
virtual void osg::DrawElements::setElement (unsigned int, unsigned int) [pure virtual]
Implemented in osg::DrawElementsUByte, osg::DrawElementsUShort, and osg::DrawElementsUInt.
void osg::DrawElements::setElementBufferObject (osg::ElementBufferObject * ebo) [inline]
Set the ElementBufferObject.
References _ebo, and osg::ref_ptr< T >::valid().
void osg::DrawElements::setElementBufferObjectOffset (const GLvoid * offset) const [inline]
Set the offset into the ElementBufferObject, if used.
References _eboOffset.
Member Data Documentation
osg::ref_ptr<ElementBufferObject> osg::DrawElements::_ebo [protected]
Referenced by dirty(), getElementBufferObject(), releaseGLObjects(), resizeGLObjectBuffers(), setElementBufferObject(), and ~DrawElements().
const GLvoid* osg::DrawElements::_eboOffset [mutable, protected]
Referenced by getElementBufferObjectOffset(), and setElementBufferObjectOffset().
The documentation for this class was generated from the following file:
osg/PrimitiveSet
Generated at Thu Jun 9 2011 10:20:37 for the OpenSceneGraph by doxygen 1.7.3.