OpenSceneGraph: osgWidget::EventInterface Class Reference
osgWidget::EventInterface Class Reference
Public Member Functions
EventInterface ()
EventInterface (const EventInterface &ei)
virtual ~EventInterface ()
virtual bool focus (WindowManager *)
virtual bool unfocus (WindowManager *)
virtual bool mouseEnter (double, double, WindowManager *)
virtual bool mouseOver (double, double, WindowManager *)
virtual bool mouseLeave (double, double, WindowManager *)
virtual bool mouseDrag (double, double, WindowManager *)
virtual bool mousePush (double, double, WindowManager *)
virtual bool mouseRelease (double, double, WindowManager *)
virtual bool mouseScroll (double, double, WindowManager *)
virtual bool keyDown (int, int, WindowManager *)
virtual bool keyUp (int, int, WindowManager *)
void setEventMask (unsigned int mask)
void addEventMask (unsigned int mask)
void removeEventMask (unsigned int mask)
unsigned int getEventMask () const
void addCallback (Callback *cb)
bool callCallbacks (Event &ev)
bool callMethodAndCallbacks (Event &ev)
bool canFocus () const
bool canUnfocus () const
bool canMouseEnter () const
bool canMouseOver () const
bool canMouseLeave () const
bool canMouseDrag () const
bool canMousePush () const
bool canMouseRelease () const
bool canMouseScroll () const
bool canKeyDown () const
bool canKeyUp () const
Constructor & Destructor Documentation
osgWidget::EventInterface::EventInterface () [inline]
osgWidget::EventInterface::EventInterface (const EventInterface & ei) [inline]
virtual osgWidget::EventInterface::~EventInterface () [inline, virtual]
Member Function Documentation
void osgWidget::EventInterface::addCallback (Callback * cb) [inline]
void osgWidget::EventInterface::addEventMask (unsigned int mask) [inline]
bool osgWidget::EventInterface::callCallbacks (Event & ev) [inline]
References osgWidget::EVENT_NONE, osgWidget::Event::setData(), and osgWidget::Event::type.
bool osgWidget::EventInterface::callMethodAndCallbacks (Event & ev) [inline]
References osgWidget::EVENT_FOCUS, osgWidget::EVENT_KEY_DOWN, osgWidget::EVENT_KEY_UP, osgWidget::EVENT_MOUSE_DRAG, osgWidget::EVENT_MOUSE_ENTER, osgWidget::EVENT_MOUSE_LEAVE, osgWidget::EVENT_MOUSE_OVER, osgWidget::EVENT_MOUSE_PUSH, osgWidget::EVENT_MOUSE_RELEASE, osgWidget::EVENT_MOUSE_SCROLL, osgWidget::EVENT_NONE, osgWidget::EVENT_UNFOCUS, osgWidget::Event::getWindowManager(), osgWidget::Event::key, osgWidget::Event::keyMask, osgWidget::Event::type, osgWidget::Event::x, and osgWidget::Event::y.
bool osgWidget::EventInterface::canFocus () const [inline]
References osgWidget::EVENT_FOCUS.
bool osgWidget::EventInterface::canKeyDown () const [inline]
References osgWidget::EVENT_KEY_DOWN.
bool osgWidget::EventInterface::canKeyUp () const [inline]
References osgWidget::EVENT_KEY_UP.
bool osgWidget::EventInterface::canMouseDrag () const [inline]
References osgWidget::EVENT_MOUSE_DRAG.
bool osgWidget::EventInterface::canMouseEnter () const [inline]
References osgWidget::EVENT_MOUSE_ENTER.
bool osgWidget::EventInterface::canMouseLeave () const [inline]
References osgWidget::EVENT_MOUSE_LEAVE.
bool osgWidget::EventInterface::canMouseOver () const [inline]
References osgWidget::EVENT_MOUSE_OVER.
bool osgWidget::EventInterface::canMousePush () const [inline]
References osgWidget::EVENT_MOUSE_PUSH.
bool osgWidget::EventInterface::canMouseRelease () const [inline]
References osgWidget::EVENT_MOUSE_RELEASE.
bool osgWidget::EventInterface::canMouseScroll () const [inline]
References osgWidget::EVENT_MOUSE_SCROLL.
bool osgWidget::EventInterface::canUnfocus () const [inline]
References osgWidget::EVENT_UNFOCUS.
virtual bool osgWidget::EventInterface::focus (WindowManager *) [inline, virtual]
Reimplemented in osgWidget::Input.
unsigned int osgWidget::EventInterface::getEventMask () const [inline]
Referenced by osgWidget::WindowManager::getFirstEventInterface().
virtual bool osgWidget::EventInterface::keyDown (int , int , WindowManager *) [inline, virtual]
Reimplemented in osgWidget::Input.
virtual bool osgWidget::EventInterface::keyUp (int , int , WindowManager *) [inline, virtual]
Reimplemented in osgWidget::Input.
virtual bool osgWidget::EventInterface::mouseDrag (double , double , WindowManager *) [inline, virtual]
Reimplemented in osgWidget::Frame::Corner, and osgWidget::Frame::Border.
virtual bool osgWidget::EventInterface::mouseEnter (double , double , WindowManager *) [inline, virtual]
virtual bool osgWidget::EventInterface::mouseLeave (double , double , WindowManager *) [inline, virtual]
virtual bool osgWidget::EventInterface::mouseOver (double , double , WindowManager *) [inline, virtual]
virtual bool osgWidget::EventInterface::mousePush (double , double , WindowManager *) [inline, virtual]
virtual bool osgWidget::EventInterface::mouseRelease (double , double , WindowManager *) [inline, virtual]
virtual bool osgWidget::EventInterface::mouseScroll (double , double , WindowManager *) [inline, virtual]
void osgWidget::EventInterface::removeEventMask (unsigned int mask) [inline]
void osgWidget::EventInterface::setEventMask (unsigned int mask) [inline]
Referenced by osgWidget::NotifyWidget::NotifyWidget(), and osgWidget::NullWidget::NullWidget().
virtual bool osgWidget::EventInterface::unfocus (WindowManager *) [inline, virtual]
Reimplemented in osgWidget::Input.
The documentation for this class was generated from the following file:
osgWidget/EventInterface
Generated at Thu Jun 9 2011 10:20:43 for the OpenSceneGraph by doxygen 1.7.3.