OpenSceneGraph: osgUtil::Optimizer::IsOperationPermissibleForObjectCallback Struct Reference
osgUtil::Optimizer::IsOperationPermissibleForObjectCallback Struct Reference
Callback for customizing what operations are permitted on objects in the scene graph.
Public Member Functions
virtual bool isOperationPermissibleForObjectImplementation (const Optimizer *optimizer, const osg::StateSet *stateset, unsigned int option) const
virtual bool isOperationPermissibleForObjectImplementation (const Optimizer *optimizer, const osg::StateAttribute *attribute, unsigned int option) const
virtual bool isOperationPermissibleForObjectImplementation (const Optimizer *optimizer, const osg::Drawable *drawable, unsigned int option) const
virtual bool isOperationPermissibleForObjectImplementation (const Optimizer *optimizer, const osg::Node *node, unsigned int option) const
Detailed Description
Callback for customizing what operations are permitted on objects in the scene graph.
Member Function Documentation
virtual bool osgUtil::Optimizer::IsOperationPermissibleForObjectCallback::isOperationPermissibleForObjectImplementation (const Optimizer * optimizer, const osg::StateSet * stateset, unsigned int option) const [inline, virtual]
References osgUtil::Optimizer::isOperationPermissibleForObjectImplementation().
Referenced by osgUtil::Optimizer::isOperationPermissibleForObject().
virtual bool osgUtil::Optimizer::IsOperationPermissibleForObjectCallback::isOperationPermissibleForObjectImplementation (const Optimizer * optimizer, const osg::Node * node, unsigned int option) const [inline, virtual]
References osgUtil::Optimizer::isOperationPermissibleForObjectImplementation().
virtual bool osgUtil::Optimizer::IsOperationPermissibleForObjectCallback::isOperationPermissibleForObjectImplementation (const Optimizer * optimizer, const osg::Drawable * drawable, unsigned int option) const [inline, virtual]
References osgUtil::Optimizer::isOperationPermissibleForObjectImplementation().
virtual bool osgUtil::Optimizer::IsOperationPermissibleForObjectCallback::isOperationPermissibleForObjectImplementation (const Optimizer * optimizer, const osg::StateAttribute * attribute, unsigned int option) const [inline, virtual]
References osgUtil::Optimizer::isOperationPermissibleForObjectImplementation().
The documentation for this struct was generated from the following file:
osgUtil/Optimizer
Generated at Thu Jun 9 2011 10:20:43 for the OpenSceneGraph by doxygen 1.7.3.