OpenSceneGraph: osg::NodeCallback Class Reference
osg::NodeCallback Class Reference
Public Member Functions
NodeCallback ()
NodeCallback (const NodeCallback &nc, const CopyOp &)
META_Object (osg, NodeCallback)
virtual void operator() (Node *node, NodeVisitor *nv)
Callback method called by the NodeVisitor when visiting a node.
void traverse (Node *node, NodeVisitor *nv)
Call any nested callbacks and then traverse the scene graph.
void setNestedCallback (NodeCallback *nc)
NodeCallback * getNestedCallback ()
const NodeCallback * getNestedCallback () const
void addNestedCallback (NodeCallback *nc)
void removeNestedCallback (NodeCallback *nc)
Public Attributes
ref_ptr< NodeCallback > _nestedCallback
Protected Member Functions
virtual ~NodeCallback ()
Constructor & Destructor Documentation
osg::NodeCallback::NodeCallback () [inline]
osg::NodeCallback::NodeCallback (const NodeCallback & nc, const CopyOp &) [inline]
virtual osg::NodeCallback::~NodeCallback () [inline, protected, virtual]
Member Function Documentation
void osg::NodeCallback::addNestedCallback (NodeCallback * nc) [inline]
References addNestedCallback().
Referenced by addNestedCallback().
NodeCallback* osg::NodeCallback::getNestedCallback () [inline]
Referenced by osg::Node::removeCullCallback(), osg::Node::removeEventCallback(), removeNestedCallback(), and osg::Node::removeUpdateCallback().
const NodeCallback* osg::NodeCallback::getNestedCallback () const [inline]
osg::NodeCallback::META_Object (osg , NodeCallback)
virtual void osg::NodeCallback::operator() (Node * node, NodeVisitor * nv) [inline, virtual]
Callback method called by the NodeVisitor when visiting a node.
Reimplemented in osg::AnimationPathCallback, osg::ClusterCullingCallback, osg::NodeTrackerCallback, osgGA::GUIEventHandler, osgShadow::MinimalDrawBoundsShadowMap::CameraCullCallback, osgShadow::ShadowTechnique::CameraCullCallback, osgUtil::TransformCallback, osgAnimation::AnimationManagerBase, osgAnimation::UpdateMorph, osgAnimation::Skeleton::UpdateSkeleton, osgAnimation::UpdateBone, osgAnimation::UpdateTransform, and osgAnimation::UpdateMatrixTransform.
void osg::NodeCallback::removeNestedCallback (NodeCallback * nc) [inline]
References getNestedCallback(), and removeNestedCallback().
Referenced by removeNestedCallback().
void osg::NodeCallback::setNestedCallback (NodeCallback * nc) [inline]
void osg::NodeCallback::traverse (Node * node, NodeVisitor * nv)
Call any nested callbacks and then traverse the scene graph.
Member Data Documentation
ref_ptr<NodeCallback> osg::NodeCallback::_nestedCallback
The documentation for this class was generated from the following file:
osg/NodeCallback
Generated at Thu Jun 9 2011 10:20:37 for the OpenSceneGraph by doxygen 1.7.3.