OpenSceneGraph: osg::ref_ptr< T > Class Template Reference
osg::ref_ptr< T > Class Template Reference
Smart pointer for handling referenced counted objects.
Public Types
typedef T element_type
Public Member Functions
ref_ptr ()
ref_ptr (T *ptr)
ref_ptr (const ref_ptr &rp)
template<class Other >
ref_ptr (const ref_ptr< Other > &rp)
~ref_ptr ()
ref_ptr & operator= (const ref_ptr &rp)
template<class Other >
ref_ptr & operator= (const ref_ptr< Other > &rp)
ref_ptr & operator= (T *ptr)
bool operator== (const ref_ptr &rp) const
bool operator== (const T *ptr) const
bool operator!= (const ref_ptr &rp) const
bool operator!= (const T *ptr) const
bool operator< (const ref_ptr &rp) const
operator unspecified_bool_type () const
T & operator* () const
T * operator-> () const
T * get () const
bool operator! () const
bool valid () const
T * release ()
void swap (ref_ptr &rp)
Friends
class ref_ptr
bool operator== (const T *ptr, const ref_ptr &rp)
bool operator!= (const T *ptr, const ref_ptr &rp)
Detailed Description
template<class T>
class osg::ref_ptr< T >
Smart pointer for handling referenced counted objects.
Member Typedef Documentation
template<class T> typedef T osg::ref_ptr< T >::element_type
Constructor & Destructor Documentation
template<class T> osg::ref_ptr< T >::ref_ptr () [inline]
template<class T> osg::ref_ptr< T >::ref_ptr (T * ptr) [inline]
template<class T> osg::ref_ptr< T >::ref_ptr (const ref_ptr< T > & rp) [inline]
template<class T> template<class Other > osg::ref_ptr< T >::ref_ptr (const ref_ptr< Other > & rp) [inline]
template<class T> osg::ref_ptr< T >::~ref_ptr () [inline]
Member Function Documentation
template<class T> T* osg::ref_ptr< T >::get () const [inline]
Referenced by osg::State::applyGlobalDefaultAttribute(), osg::const_pointer_cast(), osg::dynamic_pointer_cast(), osg::get_pointer(), osgParticle::Particle::getAlphaInterpolator(), osgParticle::Particle::getColorInterpolator(), osgParticle::ModularEmitter::getCounter(), osg::DrawElements::getElementBufferObject(), osg::State::getGlobalDefaultAttribute(), osg::State::getGlobalDefaultTextureAttribute(), osgUtil::DelaunayTriangulator::getInputPointArray(), osgAnimation::TemplateSampler< F >::getKeyframeContainer(), osgAnimation::TemplateSampler< F >::getKeyframeContainerTyped(), osg::CullStack::getModelViewMatrix(), osg::CullStack::getMVPW(), osgAnimation::TemplateSampler< F >::getOrCreateKeyframeContainer(), osgAnimation::TemplateChannel< SamplerType >::getOrCreateSampler(), osgUtil::DelaunayTriangulator::getOutputNormalArray(), osgFX::BumpMapping::getOverrideDiffuseTexture(), osgFX::BumpMapping::getOverrideNormalMapTexture(), osgParticle::ParticleProcessor::getParticleSystem(), osgParticle::ModularEmitter::getPlacer(), osg::CullStack::getProjectionMatrix(), osgAnimation::TemplateChannel< SamplerType >::getSampler(), osgAnimation::TemplateChannel< SamplerType >::getSamplerTyped(), osgParticle::ModularEmitter::getShooter(), osgParticle::Particle::getSizeInterpolator(), osg::RenderInfo::getState(), osgAnimation::TemplateChannel< SamplerType >::getTarget(), osgAnimation::TemplateChannel< SamplerType >::getTargetTyped(), osgUtil::DelaunayConstraint::getTriangles(), osgUtil::DelaunayTriangulator::getTriangles(), osg::RenderInfo::getUserData(), osg::CullStack::getViewport(), osg::CullStack::getWindowMatrix(), osgDB::RegisterDotOsgWrapperProxy::RegisterDotOsgWrapperProxy(), osgUtil::RegisterRenderBinProxy::RegisterRenderBinProxy(), osgAnimation::TemplateChannel< SamplerType >::setTarget(), osg::static_pointer_cast(), osgAnimation::RigGeometry::UpdateVertex::update(), osgDB::RegisterDotOsgWrapperProxy::~RegisterDotOsgWrapperProxy(), and osgUtil::RegisterRenderBinProxy::~RegisterRenderBinProxy().
template<class T> osg::ref_ptr< T >::operator unspecified_bool_type () const [inline]
template<class T> bool osg::ref_ptr< T >::operator! () const [inline]
template<class T> bool osg::ref_ptr< T >::operator!= (const ref_ptr< T > & rp) const [inline]
template<class T> bool osg::ref_ptr< T >::operator!= (const T * ptr) const [inline]
template<class T> T& osg::ref_ptr< T >::operator* () const [inline]
template<class T> T* osg::ref_ptr< T >::operator-> () const [inline]
template<class T> bool osg::ref_ptr< T >::operator< (const ref_ptr< T > & rp) const [inline]
template<class T> template<class Other > ref_ptr& osg::ref_ptr< T >::operator= (const ref_ptr< Other > & rp) [inline]
template<class T> ref_ptr& osg::ref_ptr< T >::operator= (T * ptr) [inline]
template<class T> ref_ptr& osg::ref_ptr< T >::operator= (const ref_ptr< T > & rp) [inline]
template<class T> bool osg::ref_ptr< T >::operator== (const ref_ptr< T > & rp) const [inline]
template<class T> bool osg::ref_ptr< T >::operator== (const T * ptr) const [inline]
template<class T> T* osg::ref_ptr< T >::release () [inline]
template<class T> void osg::ref_ptr< T >::swap (ref_ptr< T > & rp) [inline]
Referenced by osg::swap().
template<class T> bool osg::ref_ptr< T >::valid () const [inline]
Referenced by osg::State::applyAttribute(), osg::State::applyGlobalDefaultAttribute(), osgAnimation::TemplateChannel< SamplerType >::createKeyframeContainerFromTargetValue(), osg::DrawElements::dirty(), osg::Drawable::draw(), osg::RenderInfo::getContextID(), osgAnimation::TemplateChannel< SamplerType >::getOrCreateSampler(), osgSim::BlinkSequence::localTime(), osg::ref_ptr< osg::Sphere >::operator unspecified_bool_type(), osg::DrawElements::releaseGLObjects(), osg::DrawElements::resizeGLObjectBuffers(), osg::DrawElements::setElementBufferObject(), osgAnimation::RigGeometry::UpdateVertex::update(), and osg::DrawElements::~DrawElements().
Friends And Related Function Documentation
template<class T> bool operator!= (const T * ptr, const ref_ptr< T > & rp) [friend]
template<class T> bool operator== (const T * ptr, const ref_ptr< T > & rp) [friend]
template<class T> friend class ref_ptr [friend]
The documentation for this class was generated from the following file:
osg/ref_ptr
Generated at Thu Jun 9 2011 10:20:37 for the OpenSceneGraph by doxygen 1.7.3.