OpenSceneGraph: osgDB::TemplateSerializer< C, P > Class Template Reference
osgDB::TemplateSerializer< C, P > Class Template Reference
Public Types
typedef P(C::* GetterFunctionType)() const
typedef void(C::* SetterFunctionType)(P)
Public Member Functions
TemplateSerializer (const char *fieldName, P defaultValue, GetterFunctionType getter, SetterFunctionType setter)
bool write (osgDB::Output &fw, const osg::Object &obj)
bool read (osgDB::Input &fr, osg::Object &obj, bool &itrAdvanced)
Public Attributes
std::string _fieldName
P _default
GetterFunctionType _getter
SetterFunctionType _setter
template<typename C, typename P>
class osgDB::TemplateSerializer< C, P >
Member Typedef Documentation
template<typename C , typename P > typedef P(C::* osgDB::TemplateSerializer< C, P >::GetterFunctionType)() const
template<typename C , typename P > typedef void(C::* osgDB::TemplateSerializer< C, P >::SetterFunctionType)(P)
Constructor & Destructor Documentation
template<typename C , typename P > osgDB::TemplateSerializer< C, P >::TemplateSerializer (const char * fieldName, P defaultValue, GetterFunctionType getter, SetterFunctionType setter) [inline]
Member Function Documentation
template<typename C , typename P > bool osgDB::TemplateSerializer< C, P >::read (osgDB::Input & fr, osg::Object & obj, bool & itrAdvanced) [inline, virtual]
Implements osgDB::Serializer.
References osgDB::TemplateSerializer< C, P >::_fieldName, osgDB::TemplateSerializer< C, P >::_setter, and osgDB::Input::read().
template<typename C , typename P > bool osgDB::TemplateSerializer< C, P >::write (osgDB::Output & fw, const osg::Object & obj) [inline, virtual]
Implements osgDB::Serializer.
References osgDB::TemplateSerializer< C, P >::_default, osgDB::TemplateSerializer< C, P >::_fieldName, osgDB::TemplateSerializer< C, P >::_getter, osgDB::Output::getWriteOutDefaultValues(), and osgDB::Output::indent().
Member Data Documentation
template<typename C , typename P > P osgDB::TemplateSerializer< C, P >::_default
Referenced by osgDB::TemplateSerializer< C, P >::write().
template<typename C , typename P > std::string osgDB::TemplateSerializer< C, P >::_fieldName
Referenced by osgDB::TemplateSerializer< C, P >::read(), and osgDB::TemplateSerializer< C, P >::write().
template<typename C , typename P > GetterFunctionType osgDB::TemplateSerializer< C, P >::_getter
Referenced by osgDB::TemplateSerializer< C, P >::write().
template<typename C , typename P > SetterFunctionType osgDB::TemplateSerializer< C, P >::_setter
Referenced by osgDB::TemplateSerializer< C, P >::read().
The documentation for this class was generated from the following file:
osgDB/Serializer
Generated at Thu Jun 9 2011 10:20:40 for the OpenSceneGraph by doxygen 1.7.3.