OpenSceneGraph: osgIntrospection::TypedMethodInfo2< C, R, P0, P1 > Class Template Reference
osgIntrospection::TypedMethodInfo2< C, R, P0, P1 > Class Template Reference
Public Types
typedef R(C::* ConstFunctionType)(P0, P1) const
typedef R(C::* FunctionType)(P0, P1)
Public Member Functions
TypedMethodInfo2 (const std::string &qname, ConstFunctionType cf, const ParameterInfoList &plist, VirtualState virtualState, std::string briefHelp=std::string(), std::string detailedHelp=std::string())
TypedMethodInfo2 (const std::string &qname, FunctionType f, const ParameterInfoList &plist, VirtualState virtualState, std::string briefHelp=std::string(), std::string detailedHelp=std::string())
bool isConst () const
Returns whether the reflected method is const or not.
bool isStatic () const
Returns whether the reflected method is static or not.
Value invoke (const Value &instance, ValueList &args) const
Invokes the reflected method dynamically on the given const instance, passing it the arguments as a list of Value objects.
Value invoke (Value &instance, ValueList &args) const
Invokes the reflected method dynamically on the given instance, passing it the arguments as a list of Value objects.
template<typename C, typename R, typename P0, typename P1>
class osgIntrospection::TypedMethodInfo2< C, R, P0, P1 >
Member Typedef Documentation
template<typename C , typename R , typename P0 , typename P1 > typedef R(C::* osgIntrospection::TypedMethodInfo2< C, R, P0, P1 >::ConstFunctionType)(P0, P1) const
template<typename C , typename R , typename P0 , typename P1 > typedef R(C::* osgIntrospection::TypedMethodInfo2< C, R, P0, P1 >::FunctionType)(P0, P1)
Constructor & Destructor Documentation
template<typename C , typename R , typename P0 , typename P1 > osgIntrospection::TypedMethodInfo2< C, R, P0, P1 >::TypedMethodInfo2 (const std::string & qname, ConstFunctionType cf, const ParameterInfoList & plist, VirtualState virtualState, std::string briefHelp = std::string(), std::string detailedHelp = std::string()) [inline]
template<typename C , typename R , typename P0 , typename P1 > osgIntrospection::TypedMethodInfo2< C, R, P0, P1 >::TypedMethodInfo2 (const std::string & qname, FunctionType f, const ParameterInfoList & plist, VirtualState virtualState, std::string briefHelp = std::string(), std::string detailedHelp = std::string()) [inline]
Member Function Documentation
template<typename C , typename R , typename P0 , typename P1 > Value osgIntrospection::TypedMethodInfo2< C, R, P0, P1 >::invoke (const Value & instance, ValueList & args) const [inline, virtual]
Invokes the reflected method dynamically on the given const instance, passing it the arguments as a list of Value objects.
Reimplemented from osgIntrospection::MethodInfo.
References osgIntrospection::MethodInfo::getParameters(), osgIntrospection::Value::getType(), and osgIntrospection::variant_cast().
template<typename C , typename R , typename P0 , typename P1 > Value osgIntrospection::TypedMethodInfo2< C, R, P0, P1 >::invoke (Value & instance, ValueList & args) const [inline, virtual]
Invokes the reflected method dynamically on the given instance, passing it the arguments as a list of Value objects.
Reimplemented from osgIntrospection::MethodInfo.
References osgIntrospection::MethodInfo::getParameters(), osgIntrospection::Value::getType(), and osgIntrospection::variant_cast().
template<typename C , typename R , typename P0 , typename P1 > bool osgIntrospection::TypedMethodInfo2< C, R, P0, P1 >::isConst () const [inline, virtual]
Returns whether the reflected method is const or not.
Implements osgIntrospection::MethodInfo.
template<typename C , typename R , typename P0 , typename P1 > bool osgIntrospection::TypedMethodInfo2< C, R, P0, P1 >::isStatic () const [inline, virtual]
Returns whether the reflected method is static or not.
Implements osgIntrospection::MethodInfo.
The documentation for this class was generated from the following file:
osgIntrospection/TypedMethodInfo
Generated at Thu Jun 9 2011 10:20:41 for the OpenSceneGraph by doxygen 1.7.3.