OpenSceneGraph: osgIntrospection::TypedProtectedMethodInfo0< C, R > Class Template Reference
osgIntrospection::TypedProtectedMethodInfo0< C, R > Class Template Reference
Public Member Functions
TypedProtectedMethodInfo0 (const std::string &qname, bool isConstMethod, const ParameterInfoList &plist, VirtualState virtualState, std::string briefHelp=std::string(), std::string detailedHelp=std::string())
bool isConst () const
Returns whether the reflected method is const or not.
bool isStatic () const
Returns whether the reflected method is static or not.
Value invoke (const Value &, ValueList &) const
Invokes the reflected method dynamically on the given const instance, passing it the arguments as a list of Value objects.
Value invoke (Value &, ValueList &) const
Invokes the reflected method dynamically on the given instance, passing it the arguments as a list of Value objects.
Static Public Member Functions
static TypedProtectedMethodInfo0 * constMethod (const std::string &qname, const ParameterInfoList &plist, VirtualState virtualState, std::string briefHelp=std::string(), std::string detailedHelp=std::string())
static TypedProtectedMethodInfo0 * nonConstMethod (const std::string &qname, const ParameterInfoList &plist, VirtualState virtualState, std::string briefHelp=std::string(), std::string detailedHelp=std::string())
template<typename C, typename R>
class osgIntrospection::TypedProtectedMethodInfo0< C, R >
Constructor & Destructor Documentation
template<typename C , typename R > osgIntrospection::TypedProtectedMethodInfo0< C, R >::TypedProtectedMethodInfo0 (const std::string & qname, bool isConstMethod, const ParameterInfoList & plist, VirtualState virtualState, std::string briefHelp = std::string(), std::string detailedHelp = std::string()) [inline]
Referenced by osgIntrospection::TypedProtectedMethodInfo0< C, R >::constMethod(), and osgIntrospection::TypedProtectedMethodInfo0< C, R >::nonConstMethod().
Member Function Documentation
template<typename C , typename R > static TypedProtectedMethodInfo0* osgIntrospection::TypedProtectedMethodInfo0< C, R >::constMethod (const std::string & qname, const ParameterInfoList & plist, VirtualState virtualState, std::string briefHelp = std::string(), std::string detailedHelp = std::string()) [inline, static]
References osgIntrospection::TypedProtectedMethodInfo0< C, R >::TypedProtectedMethodInfo0().
template<typename C , typename R > Value osgIntrospection::TypedProtectedMethodInfo0< C, R >::invoke (const Value & instance, ValueList & args) const [inline, virtual]
Invokes the reflected method dynamically on the given const instance, passing it the arguments as a list of Value objects.
Reimplemented from osgIntrospection::MethodInfo.
template<typename C , typename R > Value osgIntrospection::TypedProtectedMethodInfo0< C, R >::invoke (Value & instance, ValueList & args) const [inline, virtual]
Invokes the reflected method dynamically on the given instance, passing it the arguments as a list of Value objects.
Reimplemented from osgIntrospection::MethodInfo.
template<typename C , typename R > bool osgIntrospection::TypedProtectedMethodInfo0< C, R >::isConst () const [inline, virtual]
Returns whether the reflected method is const or not.
Implements osgIntrospection::MethodInfo.
template<typename C , typename R > bool osgIntrospection::TypedProtectedMethodInfo0< C, R >::isStatic () const [inline, virtual]
Returns whether the reflected method is static or not.
Implements osgIntrospection::MethodInfo.
template<typename C , typename R > static TypedProtectedMethodInfo0* osgIntrospection::TypedProtectedMethodInfo0< C, R >::nonConstMethod (const std::string & qname, const ParameterInfoList & plist, VirtualState virtualState, std::string briefHelp = std::string(), std::string detailedHelp = std::string()) [inline, static]
References osgIntrospection::TypedProtectedMethodInfo0< C, R >::TypedProtectedMethodInfo0().
The documentation for this class was generated from the following file:
osgIntrospection/TypedMethodInfo
Generated at Thu Jun 9 2011 10:20:41 for the OpenSceneGraph by doxygen 1.7.3.