OpenSceneGraph: osgIntrospection::WAtomicValueReflector< T > Struct Template Reference
osgIntrospection::WAtomicValueReflector< T > Struct Template Reference
Public Types
typedef ValueReflector< T >
::instance_creator_type instance_creator_type
Public Member Functions
WAtomicValueReflector (const std::string &name, const std::string &ns)
WAtomicValueReflector (const std::string &qname)
template<typename T>
struct osgIntrospection::WAtomicValueReflector< T >
Member Typedef Documentation
template<typename T > typedef ValueReflector<T>::instance_creator_type osgIntrospection::WAtomicValueReflector< T >::instance_creator_type
Reimplemented from osgIntrospection::ValueReflector< T >.
Constructor & Destructor Documentation
template<typename T > osgIntrospection::WAtomicValueReflector< T >::WAtomicValueReflector (const std::string & name, const std::string & ns) [inline]
References osgIntrospection::Reflector< T >::addConstructor(), osgIntrospection::Reflector< T >::setComparator(), and osgIntrospection::Reflector< T >::setReaderWriter().
template<typename T > osgIntrospection::WAtomicValueReflector< T >::WAtomicValueReflector (const std::string & qname) [inline]
References osgIntrospection::Reflector< T >::addConstructor(), osgIntrospection::Reflector< T >::setComparator(), and osgIntrospection::Reflector< T >::setReaderWriter().
The documentation for this struct was generated from the following file:
osgIntrospection/Reflector
Generated at Thu Jun 9 2011 10:20:40 for the OpenSceneGraph by doxygen 1.7.3.